apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: foxford/kruonis
    docker:
      dockerfile: docker/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true
    useDockerCLI: true
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: kruonis
        chartPath: chart
        artifactOverrides:
          container.image: foxford/kruonis
        imageStrategy:
          helm: {}
        valuesFiles:
          - deploy/values.yaml
