apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kruonis.name" . }}
  labels:
    {{- include "kruonis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 2 }}
  serviceName: {{ include "kruonis.name" . }}-headless
  selector:
    matchLabels:
      {{- include "kruonis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kruonis.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kruonis.name" . }}-environment
                  key: RUST_LOG
            - name: APP_AGENT_LABEL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config
              mountPath: /app/App.toml
              subPath: App.toml
            {{- range $secret, $mounts := .Values.svc.credentials }}
            {{- range $mounts }}
            - name: {{ include "kruonis.volumeMountName" (list "svc" $secret }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.container.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: kruonis-config
        {{- range $secret, $mounts := .Values.svc.credentials }}
        - name: {{ include "kruonis.volumeMountName" (list "svc" $secret) }}
          secret:
            secretName: {{ $secret }}
        {{- end }}
        {{- end }}
